### ISSUE TITLE
Wrong JSON path when installing via scoop

### ISSUE THREAD

**Issue by ZenoArrow** [flyingpie/windows-terminal-quake#62]
Suggested installation command for scoop doesn't work, would suggest changing this...

scoop install https://github.com/flyingpie/windows-terminal-quake/blob/master/scoop/windows-terminal-quake.json

... to this...

scoop install https://raw.githubusercontent.com/flyingpie/windows-terminal-quake/master/scoop/windows-terminal-quake.json

Difference is that in the second command it's using the raw/plaintext version of the JSON file.

**Comment by Deliganli** [comment]
thanks a lot @ZenoArrow , when the changes have proposed the commit haven't been merged, so I guessed the url, and failed. Should be fixed once last commit merged.

**Comment by flyingpie** [comment]
Fixed (thanks to @Deliganli)

**Comment by flibX0r** [comment]
Just FYI, the link is still incorrect on the [GitHub Pages documentation](https://flyingpie.github.io/windows-terminal-quake/getting-started/get-from-scoop/). I'd make a pull request to fix it, but the docs are private.
