### ISSUE TITLE
Terminal window starts maximized

### ISSUE THREAD

**Issue by bllngr** [flyingpie/windows-terminal-quake#71]
With the default configuration of both the companion app and Windows Terminal (Preview), the Terminal windows is shown in maximized mode at the start off the companion app. Only when pressing the configured hotkey, the Terminal window is restored to the configured state, and then hides. Any subsequent activation using the hotkey shows the window as intended.

windows-terminal-quake version: 1.1.1-2021-02-07_1615
Windows Terminal Preview version: 1.7.572.0

**Comment by manu-vilachan** [comment]
Same behavior here ✋.

Windows Terminal Versión: 1.6.10571.0
windows-terminal-quake-1.1.1-2021-02-07_1615

**Comment by flyingpie** [comment]
@bllngr @manu-vilachan Thank you for reporting this! This is fixed with the next release: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0.

**Comment by bllngr** [comment]
Thanks, @flyingpie. I've just tested 1.2.0 and unfortunately, it still happens on my machine (with the default configurations of the Windows Terminal and your companion app).

**Comment by flyingpie** [comment]
@bllngr You're totally right, I tested one build, but accidentally uploaded another. There's a new upload that contains the fix, hopefully this time the problem is gone :)

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

**Comment by bllngr** [comment]
Great, with 1.2.0-2021-04-27_1623, the issue is actually fixed. Thank you for your work! 👍
